version: '3.8'

services:
  mongodb:
    image: mongo:8.0.4
    container_name: hotel_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: hotel
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
